apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blobfuse-flexvol
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany # must protecc the data.
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/blobfuse"
    secretRef:
      name: blobfusecreds
    options:
      container: # Specify the container name here
      tmppath: /tmp/blobfuse
      mountoptions: "--file-cache-timeout-in-seconds=120"
